import type { Metadata } from "next";
import { apiGet } from "@/lib/api";
import type { CollectorSchedule, ComponentHealth, LlmOperationsReport, SettingStatus, StorageReport, SystemHealth } from "@/lib/types";
import { formatBytes, formatDate, relativeTime } from "@/lib/format";
import { EmptyState, PageHeader, ServiceNotice, SectionTitle } from "@/components/ui";
import { clearSettingAction, runScheduleAction, testGeminiAction, toggleScheduleAction, updateScheduleAction, updateSettingAction, vacuumStorageAction } from "./actions";

export const metadata: Metadata = { title: "Sistem Sağlığı" };

const stateText = {
  healthy: "Sağlıklı",
  stale: "Gecikmiş",
  error: "Hata",
  pending: "İlk çalışma bekleniyor",
};
const scheduleOrder = ["news", "kap", "evaluations", "signals", "prices", "instruments", "fundamentals", "analysts", "institutional_reports", "fund_flows", "tcmb_policy", "paper_portfolio"];

function StatePill({ state }: { state: ComponentHealth["state"] }) {
  const tone = state === "healthy" ? "pill-positive" : state === "error" ? "pill-negative" : "";
  return <span className={`pill ${tone}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{stateText[state]}</span>;
}

function ComponentRow({ item }: { item: ComponentHealth }) {
  const age = item.last_success ? relativeTime(item.last_success) : "Henüz başarı kaydı yok";
  return <div className="flex flex-col gap-3 border-t px-4 py-4 first:border-t-0 sm:flex-row sm:items-center" style={{ borderColor: "var(--border)" }}><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{item.label}</p><p className="mt-1 text-[11px] text-[var(--text-muted)]">Son başarılı çalışma: {age}</p></div><StatePill state={item.state}/></div>;
}

export default async function SystemPage({ searchParams }: { searchParams: Promise<{ result?: string; message?: string }> }) {
  const [health, schedules, settings, storage, llm] = await Promise.all([apiGet<SystemHealth | null>("/health/detailed", null), apiGet<CollectorSchedule[]>("/api/schedules", []), apiGet<SettingStatus[]>("/api/settings", []), apiGet<StorageReport | null>("/api/system/storage", null), apiGet<LlmOperationsReport | null>("/api/system/llm", null)]);
  const notice = await searchParams;
  const report = health.data?.monitoring;
  const components = report ? [report.worker, ...Object.values(report.collectors)] : [];
  const healthy = components.filter((item) => item.state === "healthy").length;

  return <><PageHeader eyebrow="Operasyon · Canlı durum" title="Sistem Sağlığı" description="Altyapı bağlantıları, worker heartbeat'i ve veri toplama takvimlerini tek ekrandan yönetin." actions={health.data && <StatePill state={health.data.status === "ok" ? "healthy" : "stale"}/>}/><ServiceNotice show={!health.ok || !schedules.ok || !llm.ok}/>
    {notice.message && <div className={`mb-5 rounded-[12px] border px-4 py-3 text-sm ${notice.result === "ok" ? "text-[var(--positive)]" : "text-[var(--negative)]"}`} style={{ borderColor: notice.result === "ok" ? "var(--positive)" : "var(--negative)", background: notice.result === "ok" ? "var(--positive-soft)" : "var(--negative-soft)" }}>{notice.message}</div>}
    {!report ? <div className="panel-flat"><EmptyState title="Sağlık verisi alınamadı" description="API ve Redis bağlantısı kurulduğunda bileşen durumları burada görünecek."/></div> : <><div className="mb-6 grid gap-3 sm:grid-cols-3"><Metric label="Sağlıklı bileşen" value={`${healthy}/${components.length}`}/><Metric label="Sorun" value={String(report.problem_count)} tone={report.problem_count === 0}/><Metric label="İlk çalışma bekleyen" value={String(report.pending_count)} tone={report.pending_count === 0}/></div>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,.6fr)]"><section><SectionTitle title="Veri hatları" subtitle="Kaynak bazında tazelik ve hata durumu"/><div className="panel-flat overflow-hidden">{components.map((item) => <ComponentRow key={item.name} item={item}/>)}</div></section><aside><SectionTitle title="Altyapı" subtitle="Bağlantı kontrolleri"/><div className="panel-flat overflow-hidden"><Infrastructure label="PostgreSQL" state={health.data?.db}/><Infrastructure label="Redis" state={health.data?.redis}/><div className="border-t p-4 text-[11px] leading-5 text-[var(--text-muted)]" style={{ borderColor: "var(--border)" }}>Gecikmiş veya hatalı bileşenler, <code>N8N_WEBHOOK_URL</code> tanımlıysa saatlik tekrar sınırıyla webhook'a bildirilir.</div></div></aside></div></>}
    <section className="mt-8"><SectionTitle title="AI analiz hattı" subtitle="Günlük token bütçesi, seçili model ve iş kuyruğu"/>{!llm.data ? <div className="panel-flat"><EmptyState title="AI operasyon bilgisi alınamadı"/></div> : <LlmOperations report={llm.data}/>}</section>
    <section className="mt-8"><SectionTitle title="Tarama takvimleri" subtitle="Europe/Istanbul · Ayarlar PostgreSQL'de kalıcıdır"/>{schedules.data.length ? <div className="grid gap-3 lg:grid-cols-2">{[...schedules.data].sort((a, b) => scheduleOrder.indexOf(a.name) - scheduleOrder.indexOf(b.name)).map((item) => <ScheduleCard key={item.name} item={item}/>)}</div> : <div className="panel-flat"><EmptyState title="Takvim bilgisi alınamadı"/></div>}</section>
    <section className="mt-8"><SectionTitle title="Ayarlar" subtitle="Gemini API, model ve N8N seçenekleri container yeniden başlatılmadan Redis'te saklanır"/>{settings.data.length ? <div className="grid gap-3 lg:grid-cols-2">{settings.data.map((item) => <SettingCard key={item.key} item={item}/>)}</div> : <div className="panel-flat"><EmptyState title="Ayar bilgisi alınamadı"/></div>}<p className="mt-3 text-[11px] leading-5 text-[var(--text-muted)]">Interactions API yapılandırılmış yanıtı SSE akışıyla alır ve önerilen varsayılandır. GenerateContent mevcut entegrasyonlarla uyumluluk için korunur. Model/API değişimi yalnız yeni değerlendirmelere uygulanır.</p><GeminiTestPanel settings={settings.data}/></section>
    <section className="mt-8"><SectionTitle title="Depolama" subtitle="PostgreSQL tablo boyutları — en büyükler önce"/>{!storage.data ? <div className="panel-flat"><EmptyState title="Depolama bilgisi alınamadı"/></div> : <div className="panel-flat p-5 sm:p-6"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm"><span className="text-[var(--text-muted)]">Toplam veritabanı boyutu: </span><span className="font-semibold">{formatBytes(storage.data.database_size_bytes)}</span></p><p className="mt-0.5 text-[11px] text-[var(--text-muted)]">Eski binary ekler (kap_attachment) silindiğinde disk alanını geri kazanmak için vakumlama yapın.</p></div><form action={vacuumStorageAction}><button className="rounded-[10px] border px-3 py-2 text-xs font-semibold transition hover:bg-[var(--surface-hover)]" style={{ borderColor: "var(--border)" }}>Depolamayı Temizle (VACUUM)</button></form></div><div className="space-y-2">{storage.data.tables.map((item) => <StorageRow key={item.table} item={item} max={storage.data!.tables[0]?.size_bytes || 1}/>)}</div></div>}</section>
  </>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone?: boolean }) { return <div className="panel-flat p-5"><p className="text-[11px] font-medium uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className={`mt-3 text-2xl font-semibold ${tone === true ? "text-[var(--positive)]" : tone === false ? "text-[var(--warning)]" : ""}`}>{value}</p></div>; }
function Infrastructure({ label, state }: { label: string; state?: string }) { const ok = state === "ok"; return <div className="flex items-center gap-3 border-t px-4 py-4 first:border-t-0" style={{ borderColor: "var(--border)" }}><span className={`h-2 w-2 rounded-full ${ok ? "bg-[var(--positive)]" : "bg-[var(--negative)]"}`}/><span className="text-sm font-medium">{label}</span><span className="ml-auto text-xs text-[var(--text-muted)]">{ok ? "Bağlı" : "Hata"}</span></div>; }

function numberText(value: number) { return value.toLocaleString("tr-TR"); }
function BudgetBar({ label, used, limit }: { label: string; used: number; limit: number }) {
  const percentage = Math.round((used / Math.max(1, limit)) * 100);
  const width = Math.min(100, percentage);
  const color = percentage >= 100 ? "var(--negative)" : percentage >= 80 ? "var(--warning)" : "var(--primary)";
  return <div><div className="flex items-baseline justify-between gap-3 text-xs"><span className="font-medium">{label}</span><span className="text-[var(--text-muted)]">{numberText(used)} / {numberText(limit)} · %{percentage}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full rounded-full" style={{ width: `${width}%`, background: color }}/></div></div>;
}
function LlmOperations({ report }: { report: LlmOperationsReport }) {
  const { backlog, budget, config, today } = report;
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Analiz durumu" value={config.enabled ? "Etkin" : "Kapalı"} tone={config.enabled && !budget.exhausted}/><Metric label="Bekleyen kayıt" value={numberText(backlog.documents)}/><Metric label="Tahmini Tier 1 isteği" value={numberText(backlog.estimated_tier1_requests)}/><Metric label="Çözülmemiş hata" value={numberText(report.unresolved_failures)} tone={report.unresolved_failures === 0}/></div><div className="mt-3 grid gap-3 xl:grid-cols-2"><article className="panel-flat p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h3 className="text-sm font-semibold">Günlük token bütçesi</h3><p className="mt-1 text-xs text-[var(--text-muted)]">Worker ile aynı UTC gün penceresi</p></div><span className={`pill ${budget.exhausted ? "pill-negative" : "pill-positive"}`}>{budget.exhausted ? "Limit doldu" : "Kullanılabilir"}</span></div><div className="mt-5 space-y-5"><BudgetBar label="Girdi tokenı" {...budget.input_tokens}/><BudgetBar label="Çıktı tokenı" {...budget.output_tokens}/></div></article><article className="panel-flat p-5 sm:p-6"><h3 className="text-sm font-semibold">Bugünkü akış</h3><div className="mt-4 grid grid-cols-3 gap-3"><FlowCount label="Başarılı" value={today.succeeded} tone="positive"/><FlowCount label="Hatalı" value={today.failed} tone="negative"/><FlowCount label="Çalışıyor" value={today.running}/></div><div className="mt-5 border-t pt-4 text-xs leading-5 text-[var(--text-muted)]" style={{ borderColor: "var(--border)" }}><p>Haber kuyruğu: <span className="text-[var(--text-secondary)]">{numberText(backlog.news)}</span> · KAP kuyruğu: <span className="text-[var(--text-secondary)]">{numberText(backlog.kap)}</span></p><p>Yeniden denenecek hata: <span className="text-[var(--text-secondary)]">{numberText(backlog.retryable_failures)}</span> · 30 dk+ çalışan: <span className="text-[var(--text-secondary)]">{numberText(backlog.stale_running)}</span></p><p>Son tamamlanma: <span className="text-[var(--text-secondary)]">{today.last_completed_at ? `${formatDate(today.last_completed_at, true)} (${relativeTime(today.last_completed_at)})` : "Henüz yok"}</span></p></div></article></div><div className="panel-flat mt-3 px-5 py-4 text-xs leading-5 text-[var(--text-muted)]"><span className={`mr-2 inline-block h-2 w-2 rounded-full ${config.enabled ? "bg-[var(--positive)]" : "bg-[var(--warning)]"}`}/><span className="text-[var(--text-secondary)]">{config.api_mode}</span> · Tier 1 <span className="font-mono text-[var(--text-secondary)]">{config.tier1_model}</span> ({config.tier1_group_size} kayıt/istek) · Tier 2 <span className="font-mono text-[var(--text-secondary)]">{config.tier2_model}</span> · döngü başına en çok {config.batch_size} Tier 1 kayıt</div></>;
}
function FlowCount({ label, value, tone }: { label: string; value: number; tone?: "positive" | "negative" }) { return <div><p className="text-[11px] text-[var(--text-muted)]">{label}</p><p className={`mt-1 text-xl font-semibold ${tone === "positive" ? "text-[var(--positive)]" : tone === "negative" && value > 0 ? "text-[var(--negative)]" : ""}`}>{numberText(value)}</p></div>; }

function intervalText(minutes: number) { if (minutes % 1440 === 0) return `${minutes / 1440} günde bir`; if (minutes % 60 === 0) return `${minutes / 60} saatte bir`; return `${minutes} dakikada bir`; }
function ScheduleCard({ item }: { item: CollectorSchedule }) { return <article className="panel-flat p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{item.label}</h3><span className={`pill ${item.enabled ? "pill-positive" : ""}`}>{item.enabled ? "Etkin" : "Duraklatıldı"}</span></div><p className="mt-2 text-xs text-[var(--text-muted)]">{intervalText(item.interval_minutes)} · minimum {item.minimum_interval_minutes} dk</p></div><form action={toggleScheduleAction}><input type="hidden" name="name" value={item.name}/><input type="hidden" name="enabled" value={String(!item.enabled)}/><button className="rounded-[9px] border px-3 py-2 text-xs font-medium transition hover:bg-[var(--surface-hover)]" style={{ borderColor: "var(--border)" }}>{item.enabled ? "Duraklat" : "Etkinleştir"}</button></form></div><div className="mt-4 grid gap-2 text-[11px] text-[var(--text-muted)] sm:grid-cols-2"><p>Son kuyruğa ekleme<br/><span className="text-[var(--text-secondary)]">{item.last_enqueued_at ? formatDate(item.last_enqueued_at, true) : "Henüz yok"}</span></p><p>Sonraki çalışma<br/><span className="text-[var(--text-secondary)]">{item.next_run_at ? `${formatDate(item.next_run_at, true)} (${relativeTime(item.next_run_at)})` : "Duraklatıldı"}</span></p></div><div className="mt-4 flex flex-col gap-2 border-t pt-4 sm:flex-row" style={{ borderColor: "var(--border)" }}><form action={updateScheduleAction} className="flex min-w-0 flex-1 gap-2"><input type="hidden" name="name" value={item.name}/><input className="input min-w-0" aria-label={`${item.label} tarama aralığı`} type="number" name="interval_minutes" defaultValue={item.interval_minutes} min={item.minimum_interval_minutes} max={43200} required/><button className="shrink-0 rounded-[10px] bg-[var(--primary)] px-3 text-xs font-semibold text-[var(--primary-contrast)]">Dakika kaydet</button></form><form action={runScheduleAction}><input type="hidden" name="name" value={item.name}/><button className="h-10 w-full rounded-[10px] border px-3 text-xs font-semibold transition hover:bg-[var(--surface-hover)]" style={{ borderColor: "var(--border)" }}>Şimdi çalıştır</button></form></div></article>; }

function sourceText(source: SettingStatus["source"]) { return source === "database" ? "Özel değer (Redis)" : source === "env" ? ".env varsayılanı" : "Ayarlanmadı"; }
function SettingCard({ item }: { item: SettingStatus }) {
  const meta = <p className="mt-2 text-xs text-[var(--text-muted)]">{sourceText(item.source)}{item.updated_at && ` · ${formatDate(item.updated_at, true)}`}</p>;
  if (item.kind === "choice") {
    return <article className="panel-flat p-5"><h3 className="text-sm font-semibold">{item.label}</h3>{meta}<form action={updateSettingAction} className="mt-3 flex gap-2"><input type="hidden" name="key" value={item.key}/><select className="input min-w-0 flex-1" name="value" defaultValue={item.preview ?? ""} aria-label={item.label} required>{item.choices.map((choice) => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select><button className="shrink-0 rounded-[10px] bg-[var(--primary)] px-3 text-xs font-semibold text-[var(--primary-contrast)]">Seç</button></form>{item.source === "database" && <form action={clearSettingAction} className="mt-2"><input type="hidden" name="key" value={item.key}/><button className="text-[11px] text-[var(--text-muted)] underline">.env varsayılanına dön</button></form>}</article>;
  }
  if (item.kind === "boolean") {
    const enabled = item.preview === "true";
    return <article className="panel-flat p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{item.label}</h3><span className={`pill ${enabled ? "pill-positive" : ""}`}>{enabled ? "Etkin" : "Kapalı"}</span></div>{meta}</div><form action={updateSettingAction}><input type="hidden" name="key" value={item.key}/><input type="hidden" name="value" value={String(!enabled)}/><button className="rounded-[9px] border px-3 py-2 text-xs font-medium transition hover:bg-[var(--surface-hover)]" style={{ borderColor: "var(--border)" }}>{enabled ? "Kapat" : "Etkinleştir"}</button></form></div></article>;
  }
  return <article className="panel-flat p-5"><h3 className="text-sm font-semibold">{item.label}</h3>{meta}<p className="mt-2 truncate font-mono text-xs text-[var(--text-secondary)]">{item.preview ?? "Ayarlanmadı"}</p><form action={updateSettingAction} className="mt-3 flex gap-2"><input type="hidden" name="key" value={item.key}/><input className="input min-w-0 flex-1" type="password" name="value" placeholder={item.kind === "url" ? "https://..." : "Yeni değer"} autoComplete="off" required/><button className="shrink-0 rounded-[10px] bg-[var(--primary)] px-3 text-xs font-semibold text-[var(--primary-contrast)]">Kaydet</button></form>{item.source === "database" && <form action={clearSettingAction} className="mt-2"><input type="hidden" name="key" value={item.key}/><button className="text-[11px] text-[var(--text-muted)] underline">.env varsayılanına dön</button></form>}</article>;
}

function GeminiTestPanel({ settings }: { settings: SettingStatus[] }) {
  const apiMode = settings.find((item) => item.key === "gemini_api_mode")?.preview ?? "—";
  const tier1 = settings.find((item) => item.key === "gemini_model_tier1")?.preview ?? "—";
  const tier2 = settings.find((item) => item.key === "gemini_model_tier2")?.preview ?? "—";
  return <div className="panel-flat mt-4 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">Gemini bağlantı testi</h3><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">Batch değerlendirmesini etkinleştirmeden seçili API üzerinden tek ve küçük bir ücretli istek gönderir.</p><p className="mt-2 truncate font-mono text-[11px] text-[var(--text-secondary)]">{apiMode} · T1 {tier1} · T2 {tier2}</p></div><div className="flex flex-wrap gap-2"><form action={testGeminiAction}><input type="hidden" name="tier" value="1"/><button className="rounded-[10px] border px-3 py-2 text-xs font-semibold transition hover:bg-[var(--surface-hover)]" style={{ borderColor: "var(--border)" }}>Tier 1'i test et</button></form><form action={testGeminiAction}><input type="hidden" name="tier" value="2"/><button className="rounded-[10px] border px-3 py-2 text-xs font-semibold transition hover:bg-[var(--surface-hover)]" style={{ borderColor: "var(--border)" }}>Tier 2'yi test et</button></form></div></div></div>;
}

function StorageRow({ item, max }: { item: StorageReport["tables"][number]; max: number }) {
  const pct = Math.max(2, Math.round((item.size_bytes / max) * 100));
  return <div><div className="flex items-baseline justify-between gap-2 text-xs"><span className="font-medium">{item.table}</span><span className="text-[var(--text-muted)]">{formatBytes(item.size_bytes)} · ~{item.row_estimate.toLocaleString("tr-TR")} satır</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full rounded-full bg-[var(--primary)]" style={{ width: `${pct}%` }}/></div></div>;
}
