"""instrument ve price_daily tablolari

Revision ID: 443eb1b2c69d
Revises: 
Create Date: 2026-09-06 01:28:01.365102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443eb1b2c69d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('kap_member_oid', sa.String(length=64), nullable=False),
    sa.Column('mkk_member_oid', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('kap_member_oid')
    )
    op.create_table('price_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume_try', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('close_usd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_cap_try', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['instrument.ticker'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_daily_ticker_date')
    )
    op.create_index(op.f('ix_price_daily_date'), 'price_daily', ['date'], unique=False)
    op.create_index(op.f('ix_price_daily_ticker'), 'price_daily', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_daily_ticker'), table_name='price_daily')
    op.drop_index(op.f('ix_price_daily_date'), table_name='price_daily')
    op.drop_table('price_daily')
    op.drop_table('instrument')
    # ### end Alembic commands ###
