import type { Metadata } from "next";
import Link from "next/link";
import { apiGet } from "@/lib/api";
import type { IndexPrice, PaperPortfolio, PaperPosition, PaperSnapshot, PaperTrade } from "@/lib/types";
import { formatDate, formatMoney, formatNumber, formatPercent } from "@/lib/format";
import { EmptyState, PageHeader, ServiceNotice, SectionTitle } from "@/components/ui";
import { EquityChart } from "@/components/equity-chart";
import { Icon } from "@/components/icon";

export const metadata: Metadata = { title: "Paper Portföy" };

export default async function PortfolioPage() {
  const portfolios = await apiGet<PaperPortfolio[]>("/api/paper/portfolios", []); const portfolio = portfolios.data[0];
  const [positions, trades, performance] = portfolio ? await Promise.all([
    apiGet<PaperPosition[]>(`/api/paper/portfolios/${portfolio.id}/positions`, []), apiGet<PaperTrade[]>(`/api/paper/portfolios/${portfolio.id}/trades?limit=100`, []), apiGet<PaperSnapshot[]>(`/api/paper/portfolios/${portfolio.id}/performance?limit=365`, []),
  ]) : [{ data: [], ok: true as const }, { data: [], ok: true as const }, { data: [], ok: true as const }];
  const earliestSnapshot = performance.data.map((row) => row.snapshot_date).sort()[0];
  const indexPrices = earliestSnapshot ? await apiGet<IndexPrice[]>(`/api/index/XU100/prices?start=${earliestSnapshot}`, []) : { data: [] as IndexPrice[], ok: true as const };
  const latest = performance.data[0]; const serviceDown = !portfolios.ok || !positions.ok || !trades.ok || !performance.ok;
  return <><PageHeader eyebrow="Simülasyon · Canlı emir yok" title={portfolio?.name || "Paper Portföy"} description="Bileşik sinyal stratejisinin gerçek EOD fiyatlarıyla, risksiz ve sanal bakiye üzerinde izlenen performansı." actions={portfolio && <span className={`pill ${portfolio.status === "ACTIVE" ? "pill-positive" : ""}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{portfolio.status === "ACTIVE" ? "Aktif" : "Duraklatıldı"}</span>}/><ServiceNotice show={serviceDown}/>
    {!portfolio ? <div className="panel-flat"><EmptyState title="Paper portföy henüz oluşturulmadı" description="Paper motoru ilk çalıştığında 1.000.000 TL sanal bakiyeyle portföy otomatik oluşturulacak."/></div> : <><div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Toplam değer" value={formatMoney(latest?.total_equity ?? portfolio.initial_cash)} meta={formatPercent(latest?.total_return_pct, true)} tone={(latest?.total_return_pct ?? 0) >= 0}/><Metric label="Nakit bakiye" value={formatMoney(portfolio.cash_balance)} meta={`%${latest?.total_equity ? formatNumber(portfolio.cash_balance / latest.total_equity * 100) : "100"} nakit`}/><Metric label="Gerçekleşmemiş K/Z" value={formatMoney(latest?.unrealized_pnl)} tone={(latest?.unrealized_pnl ?? 0) >= 0}/><Metric label="Toplam komisyon" value={formatMoney(portfolio.total_fees)} meta={`${latest?.position_count ?? 0} açık pozisyon`}/></div>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(330px,.7fr)]"><div className="space-y-6"><section className="panel-flat p-5 sm:p-6"><SectionTitle title="Portföy performansı" subtitle={`${portfolio.strategy_version} · EOD değerleme`}/><EquityChart snapshots={performance.data} indexPrices={indexPrices.data}/></section><section><SectionTitle title="Açık pozisyonlar" subtitle={`${positions.data.length}/10 pozisyon`}/>{positions.data.length ? <div className="table-shell overflow-x-auto"><table className="data-table min-w-[720px]"><thead><tr><th>Hisse</th><th>Adet</th><th>Ort. maliyet</th><th>Son fiyat</th><th>Piyasa değeri</th><th>Gerç. K/Z</th><th>Ağırlık</th></tr></thead><tbody>{positions.data.map((item) => { const pnlPct = item.average_cost ? (item.last_price / item.average_cost - 1) * 100 : 0; return <tr key={item.id}><td><Link href={`/piyasalar/${item.ticker}`} className="font-semibold text-[var(--primary)]">{item.ticker}</Link></td><td>{formatNumber(item.quantity, 0)}</td><td>{formatMoney(item.average_cost)}</td><td>{formatMoney(item.last_price)}</td><td>{formatMoney(item.market_value)}</td><td className={item.unrealized_pnl >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}>{formatMoney(item.unrealized_pnl)} <span className="text-[10px]">({formatPercent(pnlPct, true)})</span></td><td>{formatPercent(latest?.weights[item.ticker])}</td></tr>; })}</tbody></table></div> : <div className="panel-flat"><EmptyState compact title="Açık pozisyon yok"/></div>}</section></div>
        <aside><SectionTitle title="Son işlemler" subtitle={`${trades.data.length} kayıt`}/><div className="panel-flat overflow-hidden">{trades.data.length ? trades.data.slice(0,12).map((item, index) => <div key={item.id} className={`p-4 ${index ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-lg ${item.side === "BUY" ? "bg-[var(--positive-soft)] text-[var(--positive)]" : "bg-[var(--negative-soft)] text-[var(--negative)]"}`}><Icon name="arrow" size={14} className={item.side === "SELL" ? "rotate-180" : ""}/></span><div><Link href={`/piyasalar/${item.ticker}`} className="text-sm font-semibold">{item.ticker}</Link><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">{formatDate(item.trade_date)} · {item.side === "BUY" ? "Alış" : "Satış"}</p></div><div className="ml-auto text-right"><p className="text-xs font-medium">{formatMoney(item.gross_amount)}</p><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">{formatNumber(item.quantity, 0)} adet</p></div></div><p className="mt-2 line-clamp-2 text-[10px] leading-4 text-[var(--text-muted)]">{item.reason}</p></div>) : <EmptyState compact title="İşlem henüz yok"/>}</div></aside></div>
      <p className="mt-5 text-[11px] leading-5 text-[var(--text-muted)]">Bu portföy tamamen sanaldır. Gerçek emir göndermez; komisyon ve fiyat kayması varsayımları içerir.</p></>}
  </>;
}

function Metric({ label, value, meta, tone }: { label: string; value: string; meta?: string; tone?: boolean }) { return <div className="panel-flat p-5"><p className="text-[11px] font-medium uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className={`mt-3 text-xl font-semibold tracking-[-0.03em] ${tone === true ? "text-[var(--positive)]" : tone === false ? "text-[var(--negative)]" : ""}`}>{value}</p>{meta && <p className="mt-1 text-xs text-[var(--text-muted)]">{meta}</p>}</div>; }
