import { DataMetric as Metric } from "@/components/ui";
import type { Metadata } from "next";
import Link from "next/link";
import { apiGet } from "@/lib/api";
import type { IndexPrice, PaperPortfolio, PaperPosition, PaperRisk, PaperSnapshot, PaperTrade } from "@/lib/types";
import { formatDate, formatMoney, formatNumber, formatPercent } from "@/lib/format";
import { EmptyState, PageHeader, ServiceNotice, SectionTitle } from "@/components/ui";
import { EquityChart } from "@/components/equity-chart";
import { Icon } from "@/components/icon";

export const metadata: Metadata = { title: "Paper Portföy" };

export default async function PortfolioPage() {
  const portfolios = await apiGet<PaperPortfolio[]>("/api/paper/portfolios", []); const portfolio = portfolios.data[0];
  const [positions, trades, performance, risk] = portfolio ? await Promise.all([
    apiGet<PaperPosition[]>(`/api/paper/portfolios/${portfolio.id}/positions`, []), apiGet<PaperTrade[]>(`/api/paper/portfolios/${portfolio.id}/trades?limit=100`, []), apiGet<PaperSnapshot[]>(`/api/paper/portfolios/${portfolio.id}/performance?limit=365`, []), apiGet<PaperRisk | null>(`/api/paper/portfolios/${portfolio.id}/risk`, null),
  ]) : [{ data: [], ok: true as const }, { data: [], ok: true as const }, { data: [], ok: true as const }, { data: null as PaperRisk | null, ok: true as const }];
  const riskData = risk.data; const exitLabels: Record<string, string> = { stop_loss: "Zarar-kes", take_profit: "Kâr-al", trailing_stop: "Trailing stop", signal: "Sinyal", rebalance: "Rebalance" };
  const earliestSnapshot = performance.data.map((row) => row.snapshot_date).sort()[0];
  const indexPrices = earliestSnapshot ? await apiGet<IndexPrice[]>(`/api/index/XU100/prices?start=${earliestSnapshot}`, []) : { data: [] as IndexPrice[], ok: true as const };
  const latest = performance.data[0]; const relative = relativeToBenchmark(performance.data, indexPrices.data); const serviceDown = !portfolios.ok || !positions.ok || !trades.ok || !performance.ok || !risk.ok;
  return <><PageHeader eyebrow="Simülasyon · Canlı emir yok" title={portfolio?.name || "Paper Portföy"} description="Bileşik sinyal stratejisinin gerçek EOD fiyatlarıyla, risksiz ve sanal bakiye üzerinde izlenen performansı." actions={portfolio && <span className={`pill ${portfolio.status === "ACTIVE" ? "pill-positive" : ""}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{portfolio.status === "ACTIVE" ? "Aktif" : "Duraklatıldı"}</span>}/><ServiceNotice show={serviceDown}/>
    {!portfolio ? <div className="panel-flat"><EmptyState title="Paper portföy henüz oluşturulmadı" description="Paper motoru ilk çalıştığında 1.000.000 TL sanal bakiyeyle portföy otomatik oluşturulacak."/></div> : <><div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Toplam değer" value={formatMoney(latest?.total_equity ?? portfolio.initial_cash)} meta={formatPercent(latest?.total_return_pct, true)} tone={(latest?.total_return_pct ?? 0) >= 0}/><Metric label="Nakit bakiye" value={formatMoney(portfolio.cash_balance)} meta={`%${latest?.total_equity ? formatNumber(portfolio.cash_balance / latest.total_equity * 100) : "100"} nakit`}/><Metric label="Gerçekleşmemiş K/Z" value={formatMoney(latest?.unrealized_pnl)} tone={(latest?.unrealized_pnl ?? 0) >= 0}/><Metric label="Toplam komisyon" value={formatMoney(portfolio.total_fees)} meta={`${latest?.position_count ?? 0} açık pozisyon`}/><Metric label="BIST100'e göre" value={relative ? formatPercent(relative.excess, true) : "—"} meta={relative ? `Portföy ${formatPercent(relative.portfolio, true)} · BIST100 ${formatPercent(relative.benchmark, true)}` : "Endeks verisi bekleniyor"} tone={relative ? relative.excess >= 0 : undefined}/></div>
      {riskData && <section className="mb-6"><SectionTitle title="Risk yönetimi" subtitle={`${riskData.observations} günlük gözlem · risk kuralları ayarlardan yönetilir`}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Maks. drawdown" value={formatPercent(-riskData.max_drawdown_pct)} meta="Zirveden en büyük düşüş" tone={riskData.max_drawdown_pct < 10 ? "positive" : "negative"}/><Metric label="Volatilite (yıllık)" value={formatPercent(riskData.volatility_pct)} meta="Günlük getiri std. sapması"/><Metric label="En büyük pozisyon" value={formatPercent(riskData.top_position_weight_pct)} meta={riskData.top_position_ticker ?? "Pozisyon yok"} tone={riskData.top_position_weight_pct <= riskData.rules.max_position_weight_pct * 1.25 ? "positive" : "warning"}/><Metric label="Nakit payı" value={formatPercent(riskData.cash_weight_pct)} meta={`Tek pozisyon tavanı %${formatNumber(riskData.rules.max_position_weight_pct, 0)}`}/></div>
        <div className="mt-3 grid gap-4 lg:grid-cols-2"><div className="panel-flat p-4"><p className="text-xs font-semibold">Sektör dağılımı</p>{riskData.sector_allocation.length ? <ul className="mt-3 space-y-2.5">{riskData.sector_allocation.map((row) => <li key={row.sector}><div className="flex items-center justify-between text-[11px]"><span>{row.sector}</span><span className="text-[var(--text-muted)]">{formatPercent(row.weight_pct)} · {formatMoney(row.value)}</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-[var(--surface-2,var(--border))]" role="img" aria-label={`${row.sector} yüzde ${row.weight_pct}`}><div className="h-full rounded-full bg-[var(--primary)]" style={{ width: `${Math.min(100, row.weight_pct)}%` }}/></div></li>)}</ul> : <EmptyState compact title="Sektör verisi yok"/>}</div>
          <div className="panel-flat p-4"><p className="text-xs font-semibold">Aktif risk kuralları</p><dl className="mt-3 grid grid-cols-2 gap-y-2 text-[11px]">{([["Zarar-kes", riskData.rules.stop_loss_pct], ["Kâr-al", riskData.rules.take_profit_pct], ["Trailing stop", riskData.rules.trailing_stop_pct], ["Sektör limiti", riskData.rules.max_sector_weight_pct]] as [string, number][]).map(([label, value]) => <div key={label} className="contents"><dt className="text-[var(--text-muted)]">{label}</dt><dd className="text-right font-medium">{value > 0 ? `%${formatNumber(value, 0)}` : "Kapalı"}</dd></div>)}<dt className="text-[var(--text-muted)]">Tek pozisyon tavanı</dt><dd className="text-right font-medium">%{formatNumber(riskData.rules.max_position_weight_pct, 0)}</dd><dt className="text-[var(--text-muted)]">Rebalance</dt><dd className="text-right font-medium">{riskData.rules.rebalance_enabled ? "Açık" : "Kapalı"}</dd></dl></div></div></section>}
      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(330px,.7fr)]"><div className="min-w-0 space-y-4"><section className="panel-flat p-4"><SectionTitle title="Portföy performansı" subtitle={`${portfolio.strategy_version} · EOD değerleme`}/><EquityChart snapshots={performance.data} indexPrices={indexPrices.data}/></section><section><SectionTitle title="Açık pozisyonlar" subtitle={`${positions.data.length}/10 pozisyon`}/>{positions.data.length ? <div className="table-shell overflow-x-auto"><table className="data-table min-w-[720px]"><thead><tr><th>Hisse</th><th>Adet</th><th>Ort. maliyet</th><th>Son fiyat</th><th>Piyasa değeri</th><th>Gerç. K/Z</th><th>Ağırlık</th></tr></thead><tbody>{positions.data.map((item) => { const pnlPct = item.average_cost ? (item.last_price / item.average_cost - 1) * 100 : 0; return <tr key={item.id}><td><Link href={`/piyasalar/${item.ticker}`} className="font-semibold text-[var(--primary)]">{item.ticker}</Link></td><td>{formatNumber(item.quantity, 0)}</td><td>{formatMoney(item.average_cost)}</td><td>{formatMoney(item.last_price)}</td><td>{formatMoney(item.market_value)}</td><td className={item.unrealized_pnl >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}>{formatMoney(item.unrealized_pnl)} <span className="text-[10px]">({formatPercent(pnlPct, true)})</span></td><td>{formatPercent(latest?.weights[item.ticker])}</td></tr>; })}</tbody></table></div> : <div className="panel-flat"><EmptyState compact title="Açık pozisyon yok"/></div>}</section></div>
        <aside><SectionTitle title="Son işlemler" subtitle={`${trades.data.length} kayıt`}/><a href={`/api/export/paper-trades?portfolio_id=${portfolio.id}`} download className="pill mb-3 transition hover:text-[var(--text)]"><Icon name="download" size={12}/>CSV indir</a><div className="panel-flat overflow-hidden">{trades.data.length ? trades.data.slice(0,12).map((item, index) => <div key={item.id} className={`p-4 ${index ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded ${item.side === "BUY" ? "bg-[var(--positive-soft)] text-[var(--positive)]" : "bg-[var(--negative-soft)] text-[var(--negative)]"}`}><Icon name="arrow" size={14} className={item.side === "SELL" ? "rotate-180" : ""}/></span><div><Link href={`/piyasalar/${item.ticker}`} className="text-sm font-semibold">{item.ticker}</Link><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">{formatDate(item.trade_date)} · {item.side === "BUY" ? "Alış" : "Satış"}{item.exit_reason && <span className="pill ml-1.5">{exitLabels[item.exit_reason] ?? item.exit_reason}</span>}</p></div><div className="ml-auto text-right"><p className="text-xs font-medium">{formatMoney(item.gross_amount)}</p><p className="mt-0.5 text-[10px] text-[var(--text-muted)]">{formatNumber(item.quantity, 0)} adet</p></div></div><p className="mt-2 line-clamp-2 text-[10px] leading-4 text-[var(--text-muted)]">{item.reason}</p></div>) : <EmptyState compact title="İşlem henüz yok"/>}</div></aside></div>
      <p className="mt-5 text-[11px] leading-5 text-[var(--text-muted)]">Bu portföy tamamen sanaldır. Gerçek emir göndermez; komisyon ve fiyat kayması varsayımları içerir.</p></>}
  </>;
}

// İlk gün sonu değerlemesinden bu yana portföy ve BIST100 değişimi (aynı tarih aralığı).
function relativeToBenchmark(snapshots: PaperSnapshot[], index: IndexPrice[]) {
  const ordered = [...snapshots].sort((a, b) => a.snapshot_date.localeCompare(b.snapshot_date));
  const first = ordered[0]; const last = ordered[ordered.length - 1];
  if (!first || !last || first === last || !first.total_equity) return null;
  const series = [...index].filter((row) => row.value > 0).sort((a, b) => a.date.localeCompare(b.date));
  const start = series.find((row) => row.date >= first.snapshot_date);
  const end = [...series].reverse().find((row) => row.date <= last.snapshot_date);
  if (!start || !end || start.date >= end.date) return null;
  const portfolio = (last.total_equity / first.total_equity - 1) * 100;
  const benchmark = (end.value / start.value - 1) * 100;
  return { portfolio, benchmark, excess: portfolio - benchmark };
}
