import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { apiGet } from "@/lib/api";
import type { CompositeSignal, Consensus, Fundamental, Instrument, Price, Recommendation } from "@/lib/types";
import { componentName, formatDate, formatMoney, formatNumber, formatPercent, signalName } from "@/lib/format";
import { Breadcrumbs, EmptyState, ScoreRing, SectionTitle } from "@/components/ui";
import { PriceChart } from "@/components/price-chart";
import { Icon } from "@/components/icon";

export async function generateMetadata({ params }: { params: Promise<{ ticker: string }> }): Promise<Metadata> { const { ticker } = await params; return { title: ticker.toUpperCase() }; }

export default async function InstrumentDetail({ params }: { params: Promise<{ ticker: string }> }) {
  const { ticker: rawTicker } = await params; const ticker = rawTicker.toUpperCase();
  const [instrument, prices, fundamentals, consensus, recommendations, signals] = await Promise.all([
    apiGet<Instrument | null>(`/api/instruments/${ticker}`, null), apiGet<Price[]>(`/api/instruments/${ticker}/prices`, []), apiGet<Fundamental[]>(`/api/fundamentals/${ticker}`, []), apiGet<Consensus[]>(`/api/analysts/${ticker}/consensus?limit=1`, []), apiGet<Recommendation[]>(`/api/analysts/${ticker}/recommendations?limit=20`, []), apiGet<CompositeSignal[]>(`/api/signals/${ticker}?limit=1`, []),
  ]);
  if (instrument.ok && !instrument.data) notFound();
  const company = instrument.data; const latest = prices.data.at(-1); const first = prices.data[0]; const change = latest && first ? ((latest.close / first.close) - 1) * 100 : null; const fundamental = fundamentals.data[0]; const view = consensus.data[0]; const signal = signals.data[0];
  return <>
    <Breadcrumbs items={[{ label: "Piyasalar", href: "/piyasalar" }, { label: ticker }]}/>
    <div className="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-[13px] bg-[var(--primary-soft)] text-sm font-bold text-[var(--primary)]">{ticker.slice(0,2)}</div><div><div className="flex items-center gap-2"><h1 className="page-title">{ticker}</h1><span className="pill pill-positive">BIST</span></div><p className="mt-1 text-sm text-[var(--text-secondary)]">{company?.name || "Şirket bilgisi yükleniyor"}</p></div></div><div className="md:text-right"><p className="text-3xl font-semibold tracking-[-0.04em]">{formatMoney(latest?.close)}</p><p className={`mt-1 text-sm font-medium ${(change ?? 0) >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}`}>{formatPercent(change, true)} <span className="font-normal text-[var(--text-muted)]">90 gün</span></p></div></div>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Bileşik skor" value={formatNumber(signal?.composite_score, 0)} suffix="/100" meta={signal ? signalName(signal.signal_label) : undefined}/><Stat label="Piyasa değeri" value={formatMoney(latest?.market_cap_try, true)}/><Stat label="Temel skor" value={formatNumber(fundamental?.fundamental_score, 0)} suffix="/100"/><Stat label="Analist potansiyeli" value={formatPercent(view?.implied_upside_pct, true)} tone={(view?.implied_upside_pct ?? 0) >= 0}/></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)]"><div className="space-y-6"><section className="panel-flat p-5 sm:p-6"><SectionTitle title="Fiyat performansı" subtitle="Son 90 günlük kapanış verisi"/><PriceChart prices={prices.data}/></section><section><SectionTitle title="Finansal görünüm" subtitle={fundamental ? `${fundamental.year}/${fundamental.period} dönemi` : "Son açıklanan dönem"}/>{fundamental ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Stat label="Gelir" value={formatMoney(fundamental.revenue, true)} meta={formatPercent(fundamental.revenue_yoy, true)}/><Stat label="Net kâr" value={formatMoney(fundamental.net_income, true)} meta={formatPercent(fundamental.net_income_yoy, true)}/><Stat label="Net marj" value={formatPercent(fundamental.net_margin)}/><Stat label="Özsermaye kârlılığı" value={formatPercent(fundamental.annualized_roe)}/><Stat label="Borç / özsermaye" value={formatNumber(fundamental.debt_to_equity, 2)}/><Stat label="Veri tamlığı" value={formatPercent(fundamental.data_completeness)}/></div> : <div className="panel-flat"><EmptyState compact title="Finansal veri bekleniyor"/></div>}</section></div>
      <div className="space-y-6">{signal && <section className="panel-flat p-5"><SectionTitle title="Bileşik görünüm" subtitle={`${signal.coverage_count}/4 bileşen · güven ${formatPercent(signal.confidence * 100)}`}/><div className="flex items-center gap-5"><ScoreRing score={signal.composite_score} label="Skor" size={92}/><div className="min-w-0 flex-1 space-y-3">{Object.entries(signal.component_scores).map(([name, score]) => <div key={name}><div className="mb-1 flex justify-between text-[11px]"><span className="text-[var(--text-secondary)]">{componentName(name)}</span><span className="font-semibold">{Math.round(score)}</span></div><div className="h-1.5 rounded-full bg-[var(--border)]"><div className="h-1.5 rounded-full bg-[var(--primary)]" style={{ width: `${score}%` }}/></div></div>)}</div></div></section>}<section className="panel-flat p-5"><SectionTitle title="Analist konsensüsü" subtitle={view ? formatDate(view.as_of_date) : "Güncel görünüm"}/>{view ? <><div className="flex items-center justify-center gap-7 py-3"><ScoreRing score={view.recommendation_score} label="Görüş" size={96}/><div><p className="text-2xl font-semibold">{formatMoney(view.average_target)}</p><p className="text-xs text-[var(--text-muted)]">Ortalama hedef</p><p className={`mt-2 text-sm font-semibold ${(view.implied_upside_pct ?? 0) >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}`}>{formatPercent(view.implied_upside_pct, true)} potansiyel</p></div></div><div className="mt-4 grid grid-cols-3 divide-x divide-[var(--border)] border-t pt-4 text-center" style={{ borderColor: "var(--border)" }}><Mini label="Al" value={view.buy_count} tone="positive"/><Mini label="Tut" value={view.hold_count}/><Mini label="Sat" value={view.sell_count} tone="negative"/></div></> : <EmptyState compact title="Konsensüs yok"/>}</section>
        <section><SectionTitle title="Kurum görüşleri" subtitle={`${recommendations.data.length} güncel kayıt`}/><div className="panel-flat overflow-hidden">{recommendations.data.length ? recommendations.data.slice(0,6).map((item, i) => <div key={`${item.institution}-${item.recommendation_date}`} className={`p-4 ${i ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{item.institution}</p><span className={`pill ${item.recommendation_normalized === "BUY" ? "pill-positive" : item.recommendation_normalized === "SELL" ? "pill-negative" : ""}`}>{item.recommendation_raw}</span></div><div className="mt-2 flex items-center gap-2 text-[11px] text-[var(--text-muted)]"><Icon name="clock" size={12}/>{formatDate(item.recommendation_date)}<span className="ml-auto">Hedef {formatMoney(item.target_price)}</span></div></div>) : <EmptyState compact title="Kurum görüşü yok"/>}</div></section>
      </div></div>
  </>;
}

function Stat({ label, value, suffix, meta, tone }: { label: string; value: string; suffix?: string; meta?: string; tone?: boolean }) { return <div className="panel-flat p-4"><p className="text-[11px] font-medium uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className={`mt-2 text-xl font-semibold tracking-[-0.03em] ${tone === true ? "text-[var(--positive)]" : tone === false ? "text-[var(--negative)]" : ""}`}>{value}<span className="ml-1 text-xs font-normal text-[var(--text-muted)]">{suffix}</span></p>{meta && <p className={`mt-1 text-xs ${meta.startsWith("+") ? "text-[var(--positive)]" : "text-[var(--text-muted)]"}`}>{meta}</p>}</div>; }
function Mini({ label, value, tone }: { label: string; value: number; tone?: "positive" | "negative" }) { return <div><p className={`text-lg font-semibold ${tone === "positive" ? "text-[var(--positive)]" : tone === "negative" ? "text-[var(--negative)]" : ""}`}>{value}</p><p className="text-[10px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p></div>; }
