import { DataMetric as Stat } from "@/components/ui";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { apiGet, isApiNotFound } from "@/lib/api";
import type { CompositeSignal, Consensus, Disclosure, Evaluation, Fundamental, Instrument, MonetaryPolicyDecision, NewsArticle, PaperPortfolio, PaperPosition, PaperTrade, Price, Recommendation, SignalHistory } from "@/lib/types";
import { componentName, eventName, formatDate, formatMoney, formatNumber, formatPercent, relativeTime, signalName, sourceName } from "@/lib/format";
import { Breadcrumbs, EmptyState, ScoreMeter, SectionTitle } from "@/components/ui";
import { PriceChart } from "@/components/price-chart";
import { SignalDrivers, SignalHistoryPanel } from "@/components/signal-history-panel";
import { Icon } from "@/components/icon";
import { WatchlistStar } from "@/components/watchlist-star";
import { normalizeTicker } from "@/lib/turkish";

export async function generateMetadata({ params }: { params: Promise<{ ticker: string }> }): Promise<Metadata> {
  const { ticker: rawTicker } = await params;
  const ticker = normalizeTicker(rawTicker);
  return { title: ticker };
}

export default async function InstrumentDetail({ params }: { params: Promise<{ ticker: string }> }) {
  const { ticker: rawTicker } = await params;
  const ticker = normalizeTicker(rawTicker);

  const [instrument, prices, fundamentals, consensus, recommendations, signals, news, disclosures, evaluations, portfolios, policy, history] = await Promise.all([
    apiGet<Instrument | null>(`/api/instruments/${ticker}`, null, { revalidate: 300 }),
    apiGet<Price[]>(`/api/instruments/${ticker}/prices?start=2000-01-01`, [], { revalidate: 60 }),
    apiGet<Fundamental[]>(`/api/fundamentals/${ticker}`, [], { revalidate: 300 }),
    apiGet<Consensus[]>(`/api/analysts/${ticker}/consensus?limit=1`, [], { revalidate: 120 }),
    apiGet<Recommendation[]>(`/api/analysts/${ticker}/recommendations?limit=20`, [], { revalidate: 120 }),
    apiGet<CompositeSignal[]>(`/api/signals/${ticker}?limit=5`, [], { revalidate: 60 }),
    apiGet<NewsArticle[]>(`/api/news?ticker=${ticker}&limit=8&mode=smart`, [], { revalidate: 30 }),
    apiGet<Disclosure[]>(`/api/disclosures?ticker=${ticker}&limit=8`, [], { revalidate: 30 }),
    apiGet<Evaluation[]>(`/api/evaluations?ticker=${ticker}&status=succeeded&limit=8`, [], { revalidate: 30 }),
    apiGet<PaperPortfolio[]>("/api/paper/portfolios", [], { revalidate: 60 }),
    apiGet<MonetaryPolicyDecision[]>("/api/macro/policy-decisions?status=PUBLISHED&limit=1", [], { revalidate: 600 }),
    apiGet<SignalHistory>(`/api/signals/${ticker}/history?limit=180`, { ticker, points: [], drivers: [] }, { revalidate: 60 }),
  ]);
  if (isApiNotFound(instrument)) notFound();
  const portfolio = portfolios.data[0];
  const [paperPositions, paperTrades] = portfolio ? await Promise.all([
    apiGet<PaperPosition[]>(`/api/paper/portfolios/${portfolio.id}/positions?ticker=${ticker}`, [], { revalidate: 30 }),
    apiGet<PaperTrade[]>(`/api/paper/portfolios/${portfolio.id}/trades?ticker=${ticker}&limit=20`, [], { revalidate: 30 }),
  ]) : [{ data: [], ok: true as const }, { data: [], ok: true as const }];

  const company = instrument.data; const latest = prices.data.at(-1); const ninetyDayStart = latest ? new Date(`${latest.date}T00:00:00`).getTime() - 90 * 86_400_000 : 0; const first = prices.data.find((row) => new Date(`${row.date}T00:00:00`).getTime() >= ninetyDayStart); const change = latest && first ? ((latest.close / first.close) - 1) * 100 : null; const fundamental = fundamentals.data[0]; const view = consensus.data[0]; const signal = signals.data[0]; const paperPosition = paperPositions.data[0]; const latestPolicy = policy.data[0];
  return <>
    <Breadcrumbs items={[{ label: "Piyasalar", href: "/piyasalar" }, { label: ticker }]}/>
    <div className="mb-5 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded bg-[var(--primary-soft)] text-sm font-bold text-[var(--primary)]">{ticker.slice(0,2)}</div><div><div className="flex items-center gap-2"><h1 className="page-title">{ticker}</h1><span className="pill pill-positive">BIST</span><WatchlistStar ticker={ticker}/></div><p className="mt-1 text-sm text-[var(--text-secondary)]">{company?.name || "Şirket bilgisi yükleniyor"}</p></div></div><div className="md:text-right"><p className="terminal-mono text-2xl font-semibold">{formatMoney(latest?.close)}</p><p className={`mt-1 text-sm font-medium ${(change ?? 0) >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}`}>{formatPercent(change, true)} <span className="font-normal text-[var(--text-muted)]">90 gün</span></p></div></div>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Bileşik skor" value={formatNumber(signal?.composite_score, 0)} suffix="/100" meta={signal ? signalName(signal.signal_label) : undefined}/><Stat label="Piyasa değeri" value={formatMoney(latest?.market_cap_try, true)}/><Stat label="Temel skor" value={formatNumber(fundamental?.fundamental_score, 0)} suffix="/100"/><Stat label="Analist potansiyeli" value={formatPercent(view?.implied_upside_pct, true)} tone={(view?.implied_upside_pct ?? 0) >= 0}/></div>
    <nav className="mb-6 flex gap-2 overflow-x-auto pb-1">{[["fiyat","Fiyat"],["skor-gecmisi","Skor"],["finansal","Finansallar"],["gorusler","Görüşler"],["gundem","Haber & KAP"],["analizler","AI & Portföy"]].map(([href,label]) => <a key={href} href={`#${href}`} className="pill whitespace-nowrap transition hover:text-[var(--primary)]">{label}</a>)}</nav>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)]"><div className="min-w-0 space-y-4"><section id="fiyat" className="panel-flat scroll-mt-24 p-5 sm:p-4"><SectionTitle title="Fiyat ve hacim" subtitle="Tarih aralığı ve teknik katmanlar etkileşimli olarak değiştirilebilir"/><PriceChart key={ticker} ticker={ticker} prices={prices.data} error={!prices.ok}/></section><section id="skor-gecmisi" className="panel-flat scroll-mt-24 p-5 sm:p-4"><SectionTitle title="Skor geçmişi" subtitle="Bileşik skor, bileşenler ve etiket değişimleri"/><SignalHistoryPanel history={history.data} error={!history.ok}/></section><section id="neden-skor" className="scroll-mt-24"><SectionTitle title="Neden bu skor?" subtitle="Güncel skoru en çok etkileyen haber, KAP ve analist kayıtları"/><SignalDrivers history={history.data} error={!history.ok}/></section><section id="finansal" className="scroll-mt-24"><SectionTitle title="Finansal görünüm" subtitle={fundamental ? `${fundamental.year}/${fundamental.period} dönemi · ${fundamentals.data.length} dönem kayıtlı` : "Son açıklanan dönem"}/>{fundamental ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Stat label="Gelir" value={formatMoney(fundamental.revenue, true)} meta={formatPercent(fundamental.revenue_yoy, true)}/><Stat label="Net kâr" value={formatMoney(fundamental.net_income, true)} meta={formatPercent(fundamental.net_income_yoy, true)}/><Stat label="Brüt kâr" value={formatMoney(fundamental.gross_profit, true)} meta={formatPercent(fundamental.gross_margin)}/><Stat label="Faaliyet kârı" value={formatMoney(fundamental.operating_profit, true)} meta={formatPercent(fundamental.operating_margin)}/><Stat label="Faaliyet nakit akışı" value={formatMoney(fundamental.operating_cash_flow, true)} meta={formatPercent(fundamental.operating_cash_flow_margin)}/><Stat label="Serbest nakit akışı" value={formatMoney(fundamental.free_cash_flow, true)} meta={formatPercent(fundamental.free_cash_flow_margin)}/><Stat label="Nakit" value={formatMoney(fundamental.cash, true)}/><Stat label="Toplam finansal borç" value={formatMoney((fundamental.short_term_debt ?? 0) + (fundamental.long_term_debt ?? 0), true)}/><Stat label="Özsermaye" value={formatMoney(fundamental.equity, true)}/><Stat label="Cari oran" value={formatNumber(fundamental.current_ratio, 2)}/><Stat label="Borç / özsermaye" value={formatNumber(fundamental.debt_to_equity, 2)}/><Stat label="Özsermaye kârlılığı" value={formatPercent(fundamental.annualized_roe)}/></div> : <div className="panel-flat"><EmptyState compact title="Finansal veri bekleniyor"/></div>}</section></div>
      <div id="gorusler" className="scroll-mt-24 space-y-4">{signal && <section className="panel-flat p-4"><SectionTitle title="Bileşik görünüm" subtitle={`${signal.coverage_count}/4 bileşen · güven ${formatPercent(signal.confidence * 100)}`}/><div className="flex items-center gap-5"><ScoreMeter score={signal.composite_score} label="Skor" size={92}/><div className="min-w-0 flex-1 space-y-3">{Object.entries(signal.component_scores).map(([name, score]) => <div key={name}><div className="mb-1 flex justify-between text-[11px]"><span className="text-[var(--text-secondary)]">{componentName(name)}</span><span className="font-semibold">{Math.round(score)}</span></div><div className="h-1.5 rounded-full bg-[var(--border)]"><div className="h-1.5 rounded-full bg-[var(--primary)]" style={{ width: `${score}%` }}/></div></div>)}</div></div></section>}<section className="panel-flat p-4"><SectionTitle title="Analist konsensüsü" subtitle={view ? formatDate(view.as_of_date) : "Güncel görünüm"}/>{view ? <><div className="flex items-center justify-center gap-7 py-3"><ScoreMeter score={view.recommendation_score} label="Görüş" size={96}/><div><p className="text-2xl font-semibold">{formatMoney(view.average_target)}</p><p className="text-xs text-[var(--text-muted)]">Ortalama hedef</p><p className={`mt-2 text-sm font-semibold ${(view.implied_upside_pct ?? 0) >= 0 ? "text-[var(--positive)]" : "text-[var(--negative)]"}`}>{formatPercent(view.implied_upside_pct, true)} potansiyel</p></div></div><div className="mt-4 grid grid-cols-3 divide-x divide-[var(--border)] border-t pt-4 text-center" style={{ borderColor: "var(--border)" }}><Mini label="Al" value={view.buy_count} tone="positive"/><Mini label="Tut" value={view.hold_count}/><Mini label="Sat" value={view.sell_count} tone="negative"/></div></> : <EmptyState compact title="Konsensüs yok"/>}</section>
        <section><SectionTitle title="Kurum görüşleri" subtitle={`${recommendations.data.length} güncel kayıt`}/><div className="panel-flat overflow-hidden">{recommendations.data.length ? recommendations.data.slice(0,6).map((item, i) => <div key={`${item.institution}-${item.recommendation_date}`} className={`p-4 ${i ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold">{item.institution}</p><span className={`pill ${item.recommendation_normalized === "BUY" ? "pill-positive" : item.recommendation_normalized === "SELL" ? "pill-negative" : ""}`}>{item.recommendation_raw}</span></div><div className="mt-2 flex items-center gap-2 text-[11px] text-[var(--text-muted)]"><Icon name="clock" size={12}/>{formatDate(item.recommendation_date)}<span className="ml-auto">Hedef {formatMoney(item.target_price)}</span></div></div>) : <EmptyState compact title="Kurum görüşü yok"/>}</div></section>
      </div></div>
    <div id="gundem" className="mt-8 grid scroll-mt-24 gap-6 xl:grid-cols-2"><section><SectionTitle title="Şirket haberleri" subtitle={`${news.data.length} ilgili haber`}/><div className="panel-flat overflow-hidden">{news.data.length ? news.data.map((item, index) => <Link href={`/haberler/${item.id}`} key={item.id} className={`block p-4 transition hover:bg-[var(--surface-hover)] ${index ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><div className="mb-2 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="eyebrow">{sourceName(item.source)}</span>{item.impact_score != null && item.impact_score > 0 && <span className={`pill text-[10px] font-semibold ${item.impact_score >= 60 ? "pill-positive" : item.impact_score >= 40 ? "pill-primary" : "bg-[var(--surface-raised)]"}`}>{item.impact_score >= 60 ? "" : ""}Etki: {item.impact_score}</span>}</div><span className="text-[11px] text-[var(--text-muted)]">{relativeTime(item.published_at)}</span></div><p className="text-sm font-medium leading-5">{item.title}</p>{item.summary && <p className="mt-2 line-clamp-2 text-xs leading-5 text-[var(--text-muted)]">{item.summary}</p>}</Link>) : <EmptyState compact title="İlgili haber yok"/>}</div></section>
      <section><SectionTitle title="KAP bildirimleri" subtitle={`${disclosures.data.length} şirket açıklaması`}/><div className="panel-flat overflow-hidden">{disclosures.data.length ? disclosures.data.map((item, index) => <Link href={`/kap/${item.disclosure_index}`} key={item.disclosure_index} className={`block p-4 transition hover:bg-[var(--surface-hover)] ${index ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><div className="mb-2 flex items-center justify-between gap-3"><span className="pill">{item.disclosure_class || "KAP"}</span><span className="text-[11px] text-[var(--text-muted)]">{relativeTime(item.published_at)}</span></div><p className="text-sm font-medium leading-5">{item.subject || item.summary || item.kap_title}</p><p className="mt-2 text-[11px] text-[var(--text-muted)]">{item.attachment_count} ek dosya</p></Link>) : <EmptyState compact title="İlgili KAP bildirimi yok"/>}</div></section></div>
    <div id="analizler" className="mt-8 grid scroll-mt-24 gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(320px,.8fr)]"><section><SectionTitle title="AI değerlendirmeleri" subtitle={`${evaluations.data.length} ilgili analiz`}/><div className="panel-flat overflow-hidden">{evaluations.data.length ? evaluations.data.map((item, index) => <Link href={`/analizler/${item.id}`} key={item.id} className={`grid gap-3 p-4 transition hover:bg-[var(--surface-hover)] sm:grid-cols-[auto_minmax(0,1fr)_auto] sm:items-center ${index ? "border-t" : ""}`} style={{ borderColor: "var(--border)" }}><ScoreMeter score={item.impact_score} label="Etki" size={58}/><div><div className="mb-1 flex items-center gap-2"><span className="pill pill-primary">{eventName(item.event_type)}</span><span className="text-[10px] text-[var(--text-muted)]">Tier {item.tier}</span></div><p className="text-sm font-medium leading-5">{item.summary || "Değerlendirme detayı"}</p></div><span className="text-[11px] text-[var(--text-muted)]">{relativeTime(item.created_at)}</span></Link>) : <EmptyState compact title="İlgili AI değerlendirmesi yok"/>}</div></section>
      <section><SectionTitle title="Paper portföy durumu" subtitle={portfolio?.name || "Sanal portföy"}/><div className="panel-flat p-4">{paperPosition ? <><div className="grid grid-cols-2 gap-3"><Stat label="Pozisyon değeri" value={formatMoney(paperPosition.market_value)}/><Stat label="Gerçekleşmemiş K/Z" value={formatMoney(paperPosition.unrealized_pnl)} tone={paperPosition.unrealized_pnl >= 0}/><Stat label="Adet" value={formatNumber(paperPosition.quantity, 0)}/><Stat label="Ortalama maliyet" value={formatMoney(paperPosition.average_cost)}/></div><div className="mt-5 border-t pt-4" style={{ borderColor: "var(--border)" }}><p className="eyebrow mb-3">İşlem geçmişi</p>{paperTrades.data.slice(0,5).map((trade) => <div key={trade.id} className="flex items-center gap-3 py-2 text-xs"><span className={trade.side === "BUY" ? "text-[var(--positive)]" : "text-[var(--negative)]"}>{trade.side === "BUY" ? "Alış" : "Satış"}</span><span>{formatNumber(trade.quantity, 0)} adet</span><span className="ml-auto text-[var(--text-muted)]">{formatDate(trade.trade_date)}</span></div>)}</div></> : <EmptyState compact title="Bu hissede açık paper pozisyon yok" description={paperTrades.data.length ? `${paperTrades.data.length} geçmiş işlem kaydı var.` : "Sinyal koşulları oluştuğunda işlemler burada görünecek."}/>}</div></section></div>
    {latestPolicy && <Link href="/makro" className="mt-8 flex flex-col gap-4 rounded border p-5 transition hover:bg-[var(--surface-hover)] sm:flex-row sm:items-center" style={{ borderColor: "var(--border)", background: "var(--surface)" }}><span className="grid h-10 w-10 place-items-center rounded bg-[var(--primary-soft)] text-[var(--primary)]"><Icon name="building" size={18}/></span><div className="min-w-0 flex-1"><p className="eyebrow mb-1">Makro faiz ortamı</p><p className="text-sm font-semibold">TCMB politika faizi %{formatNumber(latestPolicy.policy_rate, 2)} · {latestPolicy.market_impact.overall}</p><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">{latestPolicy.market_impact.equities}</p></div><Icon name="arrow" className="text-[var(--primary)]"/></Link>}
    <p className="mt-6 text-[11px] leading-5 text-[var(--text-muted)]">Bu sayfa fiyat, finansal tablo, KAP, haber, AI, analist, makro faiz ve sanal portföy verilerini aynı hisse kodu altında birleştirir. Bilgi amaçlıdır; yatırım tavsiyesi değildir.</p>
  </>;
}

function Mini({ label, value, tone }: { label: string; value: number; tone?: "positive" | "negative" }) { return <div><p className={`text-lg font-semibold ${tone === "positive" ? "text-[var(--positive)]" : tone === "negative" ? "text-[var(--negative)]" : ""}`}>{value}</p><p className="text-[10px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p></div>; }
