import type { Metadata } from "next";
import { apiGet } from "@/lib/api";
import type { Evaluation } from "@/lib/types";
import { eventName, formatDate, formatNumber, formatPercent, sourceName } from "@/lib/format";
import { Breadcrumbs, EmptyState, ScoreRing, TickerPills } from "@/components/ui";
import { Icon } from "@/components/icon";

export const metadata: Metadata = { title: "AI Analiz Detayı" };

export default async function AnalysisDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const result = await apiGet<Evaluation | null>(`/api/evaluations/${id}`, null); const item = result.data;
  if (!item) return <div className="panel-flat"><EmptyState title="Analiz bulunamadı"/></div>;
  return <><Breadcrumbs items={[{ label: "AI Analizleri", href: "/analizler" }, { label: `#${item.id}` }]}/><div className="mb-6 grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="mb-3 flex flex-wrap gap-2"><span className="pill">{sourceName(item.source_type)}</span><span className="pill pill-primary">{eventName(item.event_type)}</span><span className="pill">Tier {item.tier}</span></div><h1 className="text-2xl font-semibold leading-tight tracking-[-0.035em] sm:text-3xl">{item.summary || "AI değerlendirmesi"}</h1><div className="mt-4"><TickerPills tickers={item.ticker_codes}/></div></div><div className="flex gap-3"><ScoreRing score={item.relevance_score} label="İlgi"/><ScoreRing score={item.impact_score} label="Etki"/></div></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-6"><section className="panel-flat p-5 sm:p-7"><p className="eyebrow mb-3">Değerlendirme gerekçesi</p><p className="whitespace-pre-wrap text-sm leading-7 text-[var(--text-secondary)]">{item.rationale || "Bu değerlendirme için ayrıntılı gerekçe bulunmuyor."}</p></section>{item.result && <section className="panel-flat p-5 sm:p-7"><p className="eyebrow mb-3">Yapılandırılmış çıktı</p><pre className="overflow-x-auto whitespace-pre-wrap text-xs leading-6 text-[var(--text-secondary)]">{JSON.stringify(item.result, null, 2)}</pre></section>}</div><aside className="panel-flat h-fit p-5"><h2 className="text-sm font-semibold">Analiz bilgileri</h2><dl className="mt-4 space-y-4"><Info label="Durum" value={item.status}/><Info label="Model" value={item.model}/><Info label="Güven" value={formatPercent((item.confidence ?? 0) * 100)}/><Info label="Duygu" value={formatNumber(item.sentiment_score, 2)}/><Info label="Zaman ufku" value={item.time_horizon || "—"}/><Info label="Token" value={formatNumber(item.total_tokens, 0)}/><Info label="Gecikme" value={item.latency_ms ? `${formatNumber(item.latency_ms, 0)} ms` : "—"}/><Info label="Oluşturuldu" value={formatDate(item.created_at, true)}/></dl><div className="mt-5 flex gap-2 border-t pt-4 text-[11px] leading-5 text-[var(--text-muted)]" style={{ borderColor: "var(--border)" }}><Icon name="activity" size={14} className="mt-0.5 shrink-0"/>Bu içerik otomatik üretilmiştir ve yatırım tavsiyesi değildir.</div></aside></div></>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-semibold uppercase tracking-wider text-[var(--text-muted)]">{label}</dt><dd className="mt-1 break-words text-xs font-medium text-[var(--text-secondary)]">{value}</dd></div>; }
